language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: false

compiler: clang

addons:
  apt:
    packages:
    - p7zip-full

python: '2.7'

env:
  global:
  - URL_PREFIX_PREFIX=https://v8.eyeofiles.com/v8- # add V8_COMMIT
  - ANDROID_NDK_ROOT=${TRAVIS_BUILD_DIR}/third_party/android-ndk-r16b
  - libv8_show_warnings="true"
  matrix:
# 7.2.502.24
  - V8_COMMIT=4d72a9931a125d21901d25d67896f0e40105bd16 ABP_OS_SCRIPT=nix
  - V8_COMMIT=4d72a9931a125d21901d25d67896f0e40105bd16 ABP_OS_SCRIPT=android

matrix:
  exclude:
  - os: linux
    env: V8_COMMIT=4d72a9931a125d21901d25d67896f0e40105bd16 ABP_OS_SCRIPT=nix
#Disabled due to linking errors for mksnapshot, see: https://eyeogmbh.atlassian.net/browse/DP-12
  - os: osx
    env: V8_COMMIT=4d72a9931a125d21901d25d67896f0e40105bd16

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip; fi
  - ./ensure_dependencies.py
  - if [[ "${ABP_OS_SCRIPT}" == "android" && "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O third_party/android-ndk.zip ; fi
  - if [[ "${ABP_OS_SCRIPT}" == "android" && "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://dl.google.com/android/repository/android-ndk-r16b-darwin-x86_64.zip -O third_party/android-ndk.zip ; fi
  - if [[ "${ABP_OS_SCRIPT}" == "android" ]]; then unzip -q third_party/android-ndk.zip -d third_party/ ; fi
  - export URL_PREFIX=${URL_PREFIX_PREFIX}${V8_COMMIT}/

script:
  - bash ./.travis/${ABP_OS_SCRIPT}-script.sh

notifications:
  email: false
