sudo: required
dist: trusty

python: '2.7'

language: cpp

addons:
  apt:
    sources:
    - 'git-core'
    - 'ubuntu-toolchain-r-test'
    - 'llvm-toolchain-precise-3.8'
    packages:
    - g++-multilib
    - binutils-gold
    - libcurl4-openssl-dev
    - git
    - g++-6
    - clang-3.8

os:
- linux

env:
  matrix:
  - BUILD_ACTION=test
  - BUILD_ACTION=android_arm ANDROID_NDK_ROOT=${TRAVIS_BUILD_DIR}/third_party/android-ndk-r12b
  - BUILD_ACTION=android_x86 ANDROID_NDK_ROOT=${TRAVIS_BUILD_DIR}/third_party/android-ndk-r12b

before_script:
  - unset CXX
  - unset CC
  - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 999
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 999
  - if [[ -z "$ANDROID_NDK_ROOT" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 999 --slave /usr/bin/g++ g++ /usr/bin/g++-6 ; fi
  - if [[ -n "$ANDROID_NDK_ROOT" ]]; then wget https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip -O third_party/android-ndk-r12b-linux-x86_64.zip ; fi
  - if [[ -n "$ANDROID_NDK_ROOT" ]]; then pushd third_party && unzip android-ndk-r12b-linux-x86_64.zip > /dev/null && popd ; fi
  - ./ensure_dependencies.py

script:
  - travis_wait 40 bash .travis/build-v8.sh 
  - make ${BUILD_ACTION}

notifications:
  email: false
